/*
 * My REST API
 * about employee & addresses
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hanna_yanchevska@epam.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Address;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AddressControllerApi
 */
//@Ignore
public class AddressControllerApiTest {

    private final AddressControllerApi api = new AddressControllerApi();

    
    /**
     * create new address
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAddressUsingPOSTTest() throws ApiException {
        Address address = null;
        Long employeeId = null;
        Address response = api.createAddressUsingPOST(address, employeeId);

        // TODO: test validations
    }
    
    /**
     * get all addresses by employee id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllAddressesByEmployeeIdUsingGETTest() throws ApiException {
        Long employeeId = null;
        List<Address> response = api.getAllAddressesByEmployeeIdUsingGET(employeeId);

        // TODO: test validations
    }
    
}
