/*
 * My REST API
 * about employee & addresses
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hanna_yanchevska@epam.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Employee;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmployeeControllerApi
 */
//@Ignore
public class EmployeeControllerApiTest {

    private final EmployeeControllerApi api = new EmployeeControllerApi();

    
    /**
     * get all employees
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void allUsingGETTest() throws ApiException {
        List<Employee> response = api.allUsingGET();
        for (Employee employee: response){
            System.out.println(employee);
        }

        // TODO: test validations
    }
    
    /**
     * create new employee
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void newEmployeeUsingPOSTTest() throws ApiException {
        Employee newEmployee = null;
        Employee response = api.newEmployeeUsingPOST(newEmployee);

        // TODO: test validations
    }
    
    /**
     * get information about employee by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oneUsingGETTest() throws ApiException {
        Long id = null;
        Employee response = api.oneUsingGET(id);

        // TODO: test validations
    }
    
}
